services:
  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: example-app-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
